[libdefaults]
    default_realm = RENTOPTION.LOCAL
    dns_lookup_realm = false
    dns_lookup_kdc = true
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true
    rdns = false
    default_ccache_name = KEYRING:persistent:%{uid}

[realms]
    RENTOPTION.LOCAL = {
        kdc = samba:88
        admin_server = samba
        default_domain = rentoption.local
    }

[domain_realm]
    .rentoption.local = RENTOPTION.LOCAL
    rentoption.local = RENTOPTION.LOCAL

[logging]
    default = FILE:/var/log/sssd/krb5.log
