[sssd]
domains = rentoption.local
config_file_version = 2
services = nss, pam, sudo

[nss]
filter_users = root, daemon, bin, sys, sync, games, man, lp, mail, news, uucp, proxy, www-data, backup, list, irc, gnats, systemd-network, systemd-resolve, systemd-timesync, systemd-journal, syslog, messagebus, tss, sshd, statd, ntp, cups, avahi, winbindd
filter_groups = root, daemon, bin, sys, adm, tty, disk, audio, video, plugdev, users, netdev, staff, sambashare

[pam]
debug_level = 0

[sudo]

[domain/rentoption.local]
id_provider = ldap
auth_provider = krb5
chpass_provider = krb5
access_provider = permit

ldap_schema = ad
ldap_id_mapping = True
ldap_referrals = false
ldap_uri = ldaps://samba:636
ldap_search_base = DC=rentoption,DC=local
ldap_tls_reqcert = never
ldap_default_bind_dn = CN=Administrator,CN=Users,DC=rentoption,DC=local
ldap_default_authtok_type = password
ldap_default_authtok = ${SAMBA_ADMIN_PASSWORD}

ldap_user_search_base = CN=Users,DC=rentoption,DC=local
ldap_user_object_class = user
ldap_user_name = sAMAccountName
ldap_user_home_directory = unixHomeDirectory
ldap_user_principal = userPrincipalName
ldap_group_search_base = DC=rentoption,DC=local
ldap_group_object_class = group
ldap_group_name = cn

krb5_server = samba:88
krb5_realm = RENTOPTION.LOCAL
krb5_canonicalize = false

use_fully_qualified_names = False
fallback_homedir = /home/%u
default_shell = /bin/bash

cache_credentials = True
enumerate = False
ldap_use_tokengroups = True
