FROM quay.io/keycloak/keycloak:26.6

ADD --chown=keycloak:keycloak --chmod=644 \
    https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc17/23.26.0.0.0/ojdbc17-23.26.0.0.0.jar \
    /opt/keycloak/providers/ojdbc17.jar

ADD --chown=keycloak:keycloak --chmod=644 \
    https://repo1.maven.org/maven2/com/oracle/database/nls/orai18n/23.26.0.0.0/orai18n-23.26.0.0.0.jar \
    /opt/keycloak/providers/orai18n.jar

ENV KC_DB=oracle
ENV KC_FEATURES=token-exchange
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

RUN /opt/keycloak/bin/kc.sh build
